"""init

Revision ID: dc9abbb0480b
Revises:
Create Date: 2025-11-10 08:30:50.150755

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dc9abbb0480b"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "incident_source",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_incident_source")),
        sa.UniqueConstraint("name", name=op.f("uq_incident_source_name")),
    )
    op.create_index(
        op.f("ix_incident_source_id"), "incident_source", ["id"], unique=False
    )
    op.create_table(
        "incident_status",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_incident_status")),
        sa.UniqueConstraint("name", name=op.f("uq_incident_status_name")),
    )
    op.create_index(
        op.f("ix_incident_status_id"), "incident_status", ["id"], unique=False
    )
    op.create_table(
        "incidents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=False),
        sa.Column("status_id", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["incident_source.id"],
            name=op.f("fk_incidents_source_id_incident_source"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["status_id"],
            ["incident_status.id"],
            name=op.f("fk_incidents_status_id_incident_status"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_incidents")),
    )
    op.create_index(op.f("ix_incidents_id"), "incidents", ["id"], unique=False)
    op.create_index(
        op.f("ix_incidents_source_id"),
        "incidents",
        ["source_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_incidents_status_id"),
        "incidents",
        ["status_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_incidents_status_id"), table_name="incidents")
    op.drop_index(op.f("ix_incidents_source_id"), table_name="incidents")
    op.drop_index(op.f("ix_incidents_id"), table_name="incidents")
    op.drop_table("incidents")
    op.drop_index(op.f("ix_incident_status_id"), table_name="incident_status")
    op.drop_table("incident_status")
    op.drop_index(op.f("ix_incident_source_id"), table_name="incident_source")
    op.drop_table("incident_source")
    # ### end Alembic commands ###
